apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.app_name }}
  description: Terraform infrastructure for Azure deployment
  tags:
    - terraform
    - iac
    - azure
spec:
  type: infrastructure
  owner: user:guest
  lifecycle: production