# apiVersion: backstage.io/v1alpha1
# kind: Component
# metadata:
#   name: ${{values.app_name}}
#   description: Terraform infrastructure for Azure deployment
#   annotations:
#     github.com/project-slug: saagarsvs05/${{values.app_name}}
#   tags:
#     - terraform
#     - iac
#     - azure
# spec:
#   type: service
#   owner: development
#   lifecycle: production



apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.app_name}}
  description: IAC created using Backstage
  annotations:
    github.com/project-slug: saagarsvs05/${{values.app_name}}
spec:
  type: service
  lifecycle: experimental
  owner: development