apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.name}}
  description: A React frontend app scaffolded from Backstage
  tags:
    - react
spec:
  type: website
  lifecycle: experimental
  owner: development  