apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: aks-nodejs-template
  title: AKS Node.js Deployment
  description: Deploy Node.js app to AKS
spec:
  owner: development
  type: service

  parameters:
    - title: App Info
      required:
        - component_id
        - environment
      properties:
        component_id:
          type: string
          pattern: '^[a-z0-9-]+$'
        environment:
          type: string
          enum: [dev, qa, prod]

    - title: Container
      required:
        - docker_image
      properties:
        docker_image:
          type: string
          default: node:22-alpine
        acr_name:
          type: string

    - title: Kubernetes
      required:
        - namespace
        - resource_group
        - aks_cluster
      properties:
        namespace:
          type: string
          pattern: '^[a-z0-9-]+$'
        resource_group:
          type: string
          title: Azure Resource Group
        aks_cluster:
          type: string
          title: AKS Cluster Name

    - title: Repo
      required:
        - owner
        - repo
      properties:
        owner:
          type: string
          default: saagarsvs007
        repo:
          type: string

  steps:
    - id: fetch
      name: Fetch Template
      action: fetch:template
      input:
        url: ./template
        values:
          app_name: ${{ parameters.component_id }}
          namespace: ${{ parameters.namespace }}
          docker_image: ${{ parameters.docker_image }}
          owner: ${{ parameters.owner }}
          resource_group: ${{ parameters.resource_group }}
          aks_cluster: ${{ parameters.aks_cluster }}

    - id: publish
      name: Publish Repo
      action: publish:github
      input:
        repoUrl: github.com?owner=${{ parameters.owner }}&repo=${{ parameters.repo }}
        defaultBranch: main

    - id: register
      name: Register in Backstage
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}