replicaCount: 1
image:
  repository: saagarsvs/${{values.app_name}}
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ${{values.app_name}}-${{values.app_env}}-latest

resources:
  requests:
    cpu: 40m
    memory: 40M