apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.app_name}}
  description: A .NET Web API scaffolded from Backstage
  tags:
    - dotnet
spec:
  type: service
  lifecycle: experimental
  owner: team-dev
  system: default