apiVersion: v1
kind: Service
metadata:
  name: \${{ values.name }}-service
  namespace: \${{ values.namespace }}
  labels:
    app: \${{ values.name }}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: "$RESOURCE_GROUP"
spec:
  type: LoadBalancer
  loadBalancerIP: $BACKSTAGE_LB_IP
  selector:
    app: \${{ values.name }}
  ports:
  - port: \${{ values.servicePort }}
    targetPort: \${{ values.applicationPort }}
    protocol: TCP
    name: http