apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ name }}
  description: A Node.js REST API scaffolded from Backstage
  tags:
    - nodejs
spec:
  type: service
  lifecycle: experimental
  owner: development
  
