apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: azure-terraform-app
  title: Azure App via Terraform
spec:
  owner: development
  type: service

  parameters:
    - title: App Details
      required:
        - name
      properties:
        name:
          type: string

  steps:
    - id: fetch
      name: Fetch Template
      action: fetch:template
      input:
        url: ./template
        values:
          app_name: ${{ parameters.name }}

    - id: publish
      name: Publish Repo
      action: publish:github
      input:
        repoUrl: github.com?repo=${{ parameters.name }}&repo=${{ parameters.repo }}

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"