name: Deploy to AKS

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ '${{ secrets.AZURE_CREDENTIALS }}' }}
      
      - name: Login to ACR
        run: |
          az acr login --name ${{ '${{ secrets.ACR_NAME }}' }} --username ${{ '${{ secrets.ACR_USERNAME }}' }} --password ${{ '${{ secrets.ACR_PASS }}' }}
      
      - name: Set up short SHA
        id: vars
        run: echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-6)" >> $GITHUB_OUTPUT

      - name: Build and Push Docker image
        run: |
          docker build -t ${{ '${{ secrets.ACR_NAME }}' }}.azurecr.io/${{ values.app_name }}:${{ steps.vars.outputs.SHORT_SHA }} .
          docker push ${{ '${{ secrets.ACR_NAME }}' }}.azurecr.io/${{ values.app_name }}:${{ steps.vars.outputs.SHORT_SHA }}
      
      - name: Set AKS Context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ values.resource_group }}
          cluster-name: ${{ values.aks_cluster }}

      - name: Deploy
        run: |
          kubectl create namespace ${{ values.namespace }} || true
          kubectl apply -f k8s/