name: Deploy to AKS

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS Context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ values.resource_group }}
          cluster-name: ${{ values.aks_cluster }}

      - name: Deploy
        run: |
          kubectl create namespace ${{ values.namespace }} || true
          kubectl apply -f k8s/